# nvidia base is from https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base

ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.3.1
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing && \
    apt-get install -qy tzdata && \
    apt-get install -qy --no-install-recommends \
    build-essential \
    python3-pip python3-dev \
    python3-setuptools \
    libopenblas-dev \
    libopenmpi2 \
    openmpi-bin \
    openmpi-common \
    gfortran \
    git wget cmake sudo vim\
    libgoogle-perftools-dev pkg-config

RUN pip3 install Cython wheel setuptools_rust

### disable this for debug
#&& rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/pytorch/pytorch/archive/v1.6.0.tar.gz && \
    tar zxvf v1.6.0 && \
    cd pytorch-1.6.0

# PyCUDA
#ENV PATH="/usr/local/cuda/bin:${PATH}"
#ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
#RUN echo "$PATH" && echo "$LD_LIBRARY_PATH"
#RUN pip3 install pycuda --verbose

WORKDIR workspace
#RUN pip3 install python3-scipy python3-numpy scikit-learn
# install pip3 tools

# install google sentencepiece
#RUN git clone https://github.com/google/sentencepiece.git
#RUN cd sentencepiece && mkdir build && cd build && \
#    cmake .. && make -j $(nproc) && make install && \
#    cd ../python && python3 setup.py install
#RUN pip3 install transformers

#RUN git clone https://github.com/hasbegun/ParlAI.git && \
#    cd ParlAI && \
#    pip3 install -r requirements.txt && \
#    sudo python3 setup.py develop && \
#    cd .. && sudo rm -rf ParlAI

RUN rm -rf sentencepiece

CMD ['/bin/bash']
