FROM nvcr.io/nvidia/l4t-base:r32.3.1

RUN apt-get update && apt-get install -y --no-install-recommends make g++
COPY ./samples /tmp/samples
ENV PATH="/usr/local/cuda/bin:${PATH}"

WORKDIR /tmp/samples/1_Utilities/deviceQuery

RUN make clean && make

CMD ["./deviceQuery"]
