# nvidia base is from https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base
# l4t-ml:r32.4.3-py3
# TensorFlow 1.15
# PyTorch v1.6.0-rc1
# torchvision v0.7.0-rc1
# torchaudio v0.6.0-rc1
# onnx 1.7.0
# CuPy 8.0.0
# numpy 1.19.0
# numba 0.50.0
# pandas 1.0.5
# scipy 1.5.0
# scikit-learn 0.23.1
# JupyterLab 2.1.5

#ARG BASE_IMAGE=nvcr.io/nvidia/l4t-pytorch:r32.4.3-pth1.6-py3
ARG BASE_IMAGE=nvcr.io/nvidia/l4t-ml:r32.4.3-py3
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing && \
    apt-get install -qy tzdata && \
    apt-get install -qy --no-install-recommends \
    build-essential \
    python3-pip python3-dev \
    libopenblas-dev \
    libopenmpi2 \
    openmpi-bin \
    openmpi-common \
    gfortran \
    git wget cmake sudo vim\
    libgoogle-perftools-dev pkg-config

### disable this for debug
#&& rm -rf /var/lib/apt/lists/*

# install pip3 tools
RUN pip3 install setuptools Cython wheel setuptools_rust

# PyCUDA
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
RUN echo "$PATH" && echo "$LD_LIBRARY_PATH"
RUN pip3 install pycuda --verbose

WORKDIR workspace
#RUN pip3 install python3-scipy python3-numpy scikit-learn

# install google sentencepiece
RUN git clone https://github.com/google/sentencepiece.git
RUN cd sentencepiece && mkdir build && cd build && \
    cmake .. && make -j $(nproc) && make install && \
    cd ../python && python3 setup.py install

RUN git clone https://github.com/hasbegun/ParlAI.git && \
    cd ParlAI && \
    pip3 install -r requirements.txt && \
    sudo python3 setup.py develop && \
    cd .. && sudo rm -rf ParlAI

RUN rm -rf sentencepiece

CMD ['/bin/bash']
